baseURL = "/"
languageCode = "en-us"
title = "GraphQL API Slides"
theme = "reveal-hugo"

googleAnalytics = "G-VK5STNK5K8"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
